'\" t
.\"     Title: agentcrypt
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 06/12/2022
.\"    Manual: User Commands
.\"    Source: agentcrypt 1.0.6
.\"  Language: English
.\"
.TH "AGENTCRYPT" "1" "06/12/2022" "agentcrypt 1\&.0\&.6" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
agentcrypt \- Symmetric encryption with SSH Agent
.SH "SYNOPSIS"
.sp
\fBagentcrypt\fR [\fIOPTION\fR]\&... [\fIFILE\fR]\&...
.SH "DESCRIPTION"
.sp
\fBagentcrypt\fR allows using the keys in the SSH Agent to perform symmetric, authenticated encryption and decryption securely without typing passwords\&. It works with both RSA and ED25519 SSH keys including those made available to a remote host by SSH Agent forwarding\&.
.sp
Whenever possible each file is replaced by one with the \fB\&.acb\fR or \fB\&.act\fR extension (the latter when text mode is enabled) while keeping the same ownership modes, access and modification times\&. Only regular files are processed\&. In particular symbolic links are ignored\&. Encrypted files can be restored to their original form using \fBagentcrypt \-d\fR\&.
.SH "OPTIONS"
.PP
\fB\-c\fR
.RS 4
By default
\fBagentcrypt\fR
encrypts or decrypts
\fIFILEs\fR
in place\&. This option makes it write on
\fBstdout\fR
instead, leaving
\fIFILEs\fR
unchanged\&.
.RE
.PP
\fB\-d\fR
.RS 4
Enable decrypt mode (default is encrypt)
.RE
.PP
\fB\-e\fR \fIFINGERPRINT\fR
.RS 4
Encrypt using a ssh key with the specified SHA256
\fIFINGERPRINT\fR, which may or may not include the "SHA256:" prefix\&. For ease of use
\fIFINGERPRINT\fR
can also be shortened, as long as the beginning is specified\&. Use
\fIssh\-add \-E sha256 \-l\fR
to display fingerprints of available keys (for this to work
\fIopenssh\fR
version 6\&.8 or later is required)\&.
.RE
.PP
\fB\-f\fR
.RS 4
Do not ask confirmation before overwriting an already existing file\&. Additionally enable outputting binary encrypted data to a terminal\&.
.RE
.PP
\fB\-h\fR
.RS 4
Display a brief help
.RE
.PP
\fB\-k\fR
.RS 4
Keep (don\(cqt delete) input files
.RE
.PP
\fB\-t\fR
.RS 4
Text mode: encrypt or decrypt text line by line, output text
.RE
.PP
\fB\-v\fR
.RS 4
Verbose mode\&. Display information about files being processed\&.
.RE
.PP
\fB\-V\fR
.RS 4
Display version
.RE
.SH "USAGE"
.PP
\fBagentcrypt\fR \fIfilename\fR
.RS 4
Encrypt
\fIfilename\fR
and replace it wiht
\fIfilename\&.acb\fR
.RE
.PP
\fBagentcrypt \-k\fR \fIfilename\fR
.RS 4
Same, but keep the original
.RE
.PP
\fBagentcrypt \-e\fR \fIFINGERPRINT\fR \fIfilename\fR
.RS 4
Same, but use the ssh key with the specified
\fIFINGERPRINT\fR
.RE
.PP
\fBagentcrypt \-d\fR \fIfilename\&.acb\fR
.RS 4
Decrypt
\fIfilename\&.acb\fR
and replace it with
\fIfilename\fR
.RE
.PP
\fBtar zc\fR \fIdata\fR | \fBagentcrypt\fR > \fIdata\&.tgz\&.acb\fR
.RS 4
Archive and encrypt
\fIdata\fR
.RE
.PP
\fBagentcrypt \-c \-d\fR \fIdata\&.tgz\&.acb\fR | \fBtar zx\fR
.RS 4
Decrypt and extract
\fIdata\&.tgz\&.acb\fR
.RE
.PP
\fBagentcrypt \-t\fR \fIfilename\fR
.RS 4
Encrypt the
\fIfilename\fR
text file line by line and replace it with
\fIfilename\&.act\fR
.RE
.PP
\fBagentcrypt \-t \-d\fR \fIfilename\&.act\fR
.RS 4
Decrypt
\fIfilename\&.act\fR
line by line and replace it with
\fIfilename\fR
.RE
.PP
\fBagentcrypt \-t\fR
.RS 4
Read lines of text from stdin, encrypt them one by one and output encrypted text to stdout\&. If stdin is a terminal, disable input echo\&.
.RE
.PP
\fBagentcrypt \-t \-d\fR
.RS 4
Read encrypted lines of text from term, decrypt them one by one and output decrypted text to stdout\&.
.RE
.SH "ENVIRONMENT"
.sp
\fBagentcrypt\fR takes the path to the SSH Agent UNIX\-domain socket from the \fISSH_AUTH_SOCK\fR environment variable\&.
.sp
When using RSA keys, if the \fIAGENTCRYPT_LEGACY\fR environment variable is defined and not zero, \fBagentcrypt\fR asks the SSH Agent to produce legacy RSA SHA1 signatures during encryption\&. This is not recommended and is only necessary if the encrypted data need to be decrypted using legacy openssh versions (older than 7\&.2) whose agent did not support RSA SHA256 signatures\&. Note that data encrypted using such legacy versions can always be decrypted correctly without needing to define this variable\&.
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure (syntax or usage error; configuration error; processing failure; unexpected error)\&.
.RE
.SH "BUGS"
.sp
If you believe you have found a bug, please create a new issue at https://github\&.com/ndilieto/libagentcrypt/issues with any applicable information\&.
.SH "COPYRIGHT"
.sp
This file is part of https://github\&.com/ndilieto/libagentcrypt
.sp
Copyright (c) 2019, Nicola Di Lieto <nicola\&.dilieto@gmail\&.com>
.sp
Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies\&.
.sp
THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\&. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE\&.
